---
sudo: false

language: python

cache:
  directories:
    - $HOME/.cache/pip
    - .tox

before_install:
  - openssl aes-256-cbc -K $encrypted_4cab73570a75_key -iv $encrypted_4cab73570a75_iv -in molecule/default/clouds.yml.enc -out molecule/default/clouds.yml -d

install:
  - pip install -r requirements.txt

script:
  - detox

notifications:
  irc:
    channels:
      - "irc.freenode.org#osism"
    template:
      - "%{result} %{repository_slug}: %{commit_subject} %{build_url}"
    skip_join: true
