---
- name: Stopp/disable resolvconf service
  service:
    name: resolvconf
    state: stopped
    enabled: no
  register: result
  failed_when: "result is failed and ('find' not in result.msg and 'found' not in result.msg)"
  become: true

- name: Remove resolvconf package
  package:
    name: "{{ resolvconf_package }}"
    state: absent
  become: true
  when: resolvconf_package|length

- name: Retrieve resolv.conf file status
  stat:
    path: /etc/resolv.conf
  register: resolvconf_file

- name: Archive existing /etc/resolv.conf file
  synchronize:
    src: "/etc/resolv.conf"
    dest: "/etc/resolv.conf.{{ ansible_date_time.date }}"
    archive: yes
  become: true
  delegate_to: "{{ inventory_hostname }}"
  when: resolvconf_file.stat.islnk is defined and not resolvconf_file.stat.islnk

- name: Copy configuration files
  template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  become: true
  with_items:
    - src: bionic/resolved.conf.j2
      dest: /etc/systemd/resolved.conf
  register: resolved_conf

- name: Restart systemd-resolved service
  when: resolved_conf.changed  # noqa 503
  systemd:
    name: systemd-resolved
    daemon_reload: yes
    state: restarted
  become: true

- name: Link /etc/resolv.conf to /run/systemd/resolve/stub-resolv.conf
  file:
    src: /run/systemd/resolve/stub-resolv.conf
    dest: /etc/resolv.conf
    state: link
    force: yes
  become: true
